#[network-node]
#enable=true

[agent]

whitelist=geoclue-demo-agent;gnome-shell;chromium;google-chrome;chromium;io.elementary.desktop.agent-geoclue2;sm.puri.Phosh;lipstick;firefox-esr;firefox


# Network NMEA source configuration options
[network-nmea]
enable=true
nmea-socket=/run/gpsd-nmea.sock

[3g]

# Enable 3G source
enable=false

# CDMA source configuration options
[cdma]

# Enable CDMA source
enable=false

# Modem GPS source configuration options
[modem-gps]

# Enable Modem-GPS source
enable=false

# WiFi source configuration options
[wifi]
enable=false
#url=https://beacondb.net/v1/geolocate


[geoip]
enable=true


submit-data=false

submission-nick=geoclue

# Compass configuration options
[compass]

# Enable Compass
enable=true

# Static source configuration options
#
# This source reads location from "geolocation" file in /etc - please
# consult geoclue(5) man page for the format description of this file.
[static-source]

enable=false

[gnome-datetime-panel]
allowed=true
system=true
users=

[gnome-color-panel]
allowed=true
system=true
users=

[org.gnome.Shell]
allowed=true
system=true
users=

[io.elementary.desktop.agent-geoclue2]
allowed=true
system=true
users=

[sm.puri.Phosh]
allowed=true
system=true
users=

[epiphany]
allowed=true
system=false
users=


[lipstick]
allowed=true
system=true
users=

[gpsd]
allowed=true
system=true
users=


[firefox]
allowed=true
system=false
users=

[chromium-browser]
allowed=true
system=false
users=

[chromium]
allowed=true
system=false
users=


[google-chrome]
allowed=true
system=false
users=

[firefox-esr]
allowed=true
system=false
users=


[gnome-maps]
allowed=true
system=false
users=

